descriptors/ModuleDescriptor-template.json, doc/documentation.md, src/main/java/org/folio/entlinks/controller/InstanceLinksController.java, src/main/java/org/folio/entlinks/model/converter/InstanceLinkMapper.java, src/main/java/org/folio/entlinks/service/InstanceLinkService.java, src/main/resources/swagger.api/mod-entities-links.yaml, src/test/java/org/folio/entlinks/controller/InstanceLinksIT.java, src/test/java/org/folio/entlinks/service/InstanceLinkServiceTest.java
Create an API endpoint to return all links MARC bib has
JIRA: https://issues.folio.org/browse/MODELINKS-3
- describe API definition for GET /links/instances/<instanceId> endpoint;
- implement a service layer to retrieve all MARC bib links from the database.
- add endpoints to descriptor
- update tests
- update documentation
=> MODELINKS-3 Create an API endpoint to return all links MARC bib has

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/entlinks/controller/InstanceLinksController.java, src/main/java/org/folio/entlinks/model/converter/InstanceLinkMapper.java, src/main/java/org/folio/entlinks/model/projection/LinkCountView.java, src/main/java/org/folio/entlinks/repository/InstanceLinkRepository.java, src/main/java/org/folio/entlinks/service/InstanceLinkService.java, src/main/resources/swagger.api/mod-entities-links.yaml, src/test/java/org/folio/entlinks/controller/InstanceLinksIT.java, src/test/java/org/folio/entlinks/service/InstanceLinkServiceTest.java
As described [MODELINKS-8](https://issues.folio.org/browse/MODELINKS-8), created bulk API to retrieve total links count map for authority
=> Modelinks 8 - Create bulk API to retrieve total links count map for authority

src/main/java/org/folio/entlinks/service/messaging/authority/InstanceAuthorityLinkUpdateService.java, src/main/java/org/folio/entlinks/service/messaging/authority/handler/AbstractAuthorityChangeHandler.java, src/main/java/org/folio/entlinks/service/messaging/authority/handler/AuthorityChangeHandler.java, src/main/java/org/folio/entlinks/service/messaging/authority/handler/DeleteAuthorityChangeHandler.java, src/main/java/org/folio/entlinks/service/messaging/authority/handler/UpdateAuthorityChangeHandler.java, src/main/java/org/folio/entlinks/service/messaging/authority/model/AuthorityChangeHolder.java, src/main/java/org/folio/entlinks/service/messaging/authority/model/AuthorityChangeType.java, src/main/resources/swagger.api/mod-entities-links.yaml, src/test/java/org/folio/entlinks/integration/kafka/AuthorityInventoryEventListenerIT.java, src/test/java/org/folio/entlinks/service/messaging/authority/InstanceAuthorityLinkUpdateServiceTest.java, src/test/java/org/folio/entlinks/service/messaging/authority/handler/DeleteAuthorityChangeHandlerTest.java, src/test/java/org/folio/entlinks/utils/ObjectUtilsTest.java
Handle authority update when heading type changed
When the authority heading type changed then the value of the heading migrated from one field of authority record to another. For example, a record had 100 field with a, b, c (personalName field in inventory record), after update this field has a, b, c, t subfields. After mapping the updated record to the inventory record, it will have already a personalNameTitle field instead of personalName.
So, when we check the authority update message and compare old and new records we will have more differences:
- personalName: is null in new
- personalNameTitle: is null in old
- naturalId: could be changed or not.
So, if an event have more than 2 or 2 and any of them is not naturalId change. It becomes an authority heading type change and as …
=> MODELINKS-28 Handle authority update when heading type changed

src/main/java/org/folio/entlinks/integration/internal/AuthoritySourceFilesService.java, src/test/java/org/folio/entlinks/integration/internal/AuthoritySourceFilesServiceTest.java
Fix
- ignore authority source files with `null` in `id` or `baseUrl` fields
[MODELINKS-37](https://issues.folio.org/browse/MODELINKS-37)
=> MODELINKS-37 The controlled "MARC Bib" record doesn't respond to update of "010" field of "MARC Authority" record

pom.xml, src/main/java/org/folio/entlinks/service/messaging/authority/model/FieldChangeHolder.java, src/test/java/org/folio/entlinks/integration/kafka/AuthorityInventoryEventListenerIT.java
Fix issue when user can add controllable subfields to linked field of a "MARC bib" record after updating "1XX" in controlling "MARC authority" record. The cause of this is update of links in database was based on authority subfields and not on linking rules where all possible subfields defined.
=> MODELINKS-45 Update links with all controlled subfields

descriptors/ModuleDescriptor-template.json, doc/documentation.md, pom.xml, src/main/java/org/folio/entlinks/client/InstanceStorageClient.java, src/main/java/org/folio/entlinks/controller/LinksStatisticsInstanceController.java, src/main/java/org/folio/entlinks/controller/converter/LinkedBibUpdateStatsMapper.java, src/main/java/org/folio/entlinks/controller/delegate/LinkingServiceDelegate.java, src/main/java/org/folio/entlinks/domain/entity/InstanceAuthorityLink.java, src/main/java/org/folio/entlinks/domain/repository/InstanceLinkRepository.java, src/main/java/org/folio/entlinks/integration/internal/InstanceStorageService.java, src/main/java/org/folio/entlinks/service/links/InstanceAuthorityLinkingService.java, src/main/resources/application.yaml, src/main/resources/swagger.api/mod-entities-links.yaml, src/main/resources/swagger.api/schemas/bibStatsDto.json, src/test/java/org/folio/entlinks/controller/LinksStatisticsInstanceIT.java, src/test/java/org/folio/entlinks/controller/delegate/LinkingServiceDelegateTest.java, src/test/java/org/folio/entlinks/integration/internal/InstanceStorageServiceTest.java, src/test/java/org/folio/entlinks/service/links/InstanceAuthorityLinkingServiceTest.java, src/test/java/org/folio/support/TestUtils.java, src/test/java/org/folio/support/base/IntegrationTestBase.java, src/test/java/org/folio/support/base/TestConstants.java, src/test/resources/mappings/instance-storage.json
Needs to support reporting that allows catalogers to know about updates on linked Bibliographic fields and Authorities over a period of time. The module will consume statistics of instance-authority links updates and provide an endpoint for fetching this data.
- Add Client for instance-storage
- Create GET /links/stats/instance endpoint
- Update ModuleDescriptor-template.json
- Update documentation.md
[MODELINKS-35](https://issues.folio.org/browse/MODELINKS-35)
=> MODELINKS-35 Link update report: Create endpoint for fetching links stats (Instance)

src/main/java/org/folio/entlinks/controller/delegate/InstanceAuthorityStatServiceDelegate.java, src/test/java/org/folio/entlinks/controller/delegate/InstanceAuthorityStatServiceDelegateTest.java
Make "Last Updated" field available for MARC update-headings report CSV file
Provided metadata creation even when user does not exist
[https://issues.folio.org/browse/MODELINKS-64](https://issues.folio.org/browse/MODELINKS-64)
=> MODELINKS-64: Metadata generation is provided when startedByUser is deleted

src/main/java/org/folio/entlinks/client/AuthoritySourceFileClient.java, src/main/java/org/folio/entlinks/integration/internal/AuthoritySourceFilesService.java, src/test/java/org/folio/entlinks/integration/internal/AuthoritySourceFilesServiceTest.java, src/test/resources/mappings/authoritySourceFiles.json
"Not specified" is displayed instead of valid "Authority source file name" in the "Updates headings" report
- Add source file limit. Because previously it took only 10 first files 
https://issues.folio.org/browse/MODELINKS-69
=> MODELINKS-69 "Not specified" is displayed instead of valid "Authority source file name" in the "Updates headings" report

src/main/java/org/folio/entlinks/client/SearchClient.java, src/main/java/org/folio/entlinks/controller/converter/SourceContentMapper.java, src/main/java/org/folio/entlinks/controller/delegate/LinksSuggestionsServiceDelegate.java, src/main/java/org/folio/entlinks/service/links/InstanceAuthorityLinkingRulesService.java, src/main/java/org/folio/entlinks/service/links/LinksSuggestionService.java, src/test/java/org/folio/entlinks/controller/delegate/LinksSuggestionsServiceDelegateTest.java, src/test/resources/mappings/mod-search.json
fix(automate-linking): Suggest links for MARC-bibliographic record
- Fix `NullPointerException` when field doesn't have $0 subfield
- Don't suggest links for fields with NEW status
- Save fields/subfields order
- Fix cql build query by adding quotes
Closes MODELINKS-95
https://issues.folio.org/browse/MODELINKS-94
=> fix(automate-linking): Suggest links for MARC-bibliographic record 

NEWS.md, pom.xml, src/main/java/org/folio/entlinks/client/SearchClient.java, src/main/java/org/folio/entlinks/controller/delegate/LinksSuggestionsServiceDelegate.java, src/main/java/org/folio/entlinks/domain/entity/AuthorityData.java, src/main/java/org/folio/entlinks/integration/internal/SearchService.java, src/main/java/org/folio/entlinks/service/links/InstanceAuthorityLinkingService.java, src/test/java/org/folio/entlinks/controller/delegate/LinksSuggestionsServiceDelegateTest.java, src/test/java/org/folio/entlinks/integration/internal/SearchServiceTest.java, src/test/java/org/folio/entlinks/service/links/InstanceAuthorityLinkingServiceTest.java, src/test/resources/application-test.yaml
Fix too-long url exception in search requests while automate linking
- create a service to work with SearchClient
- do chunkable requests
https://issues.folio.org/browse/MODELINKS-111
=> fix(automate-linking): too-long url exception in search requests

src/main/java/org/folio/entlinks/controller/converter/SourceContentMapper.java, src/main/java/org/folio/entlinks/controller/delegate/LinksSuggestionsServiceDelegate.java, src/main/java/org/folio/entlinks/integration/dto/AuthorityParsedContent.java, src/main/java/org/folio/entlinks/integration/dto/FieldParsedContent.java, src/main/java/org/folio/entlinks/integration/dto/SourceParsedContent.java, src/main/java/org/folio/entlinks/service/links/AuthorityRuleValidationService.java, src/main/java/org/folio/entlinks/service/links/LinksSuggestionService.java, src/test/java/org/folio/entlinks/service/links/LinksSuggestionsServiceTest.java
Fix bug when not linked field replaced by a linked one when auto-linking fields with same tag and field with another tag between them
https://issues.folio.org/browse/MODELINKS-110
=> fix(automate-linking): incorrect order of resulting fields

descriptors/ModuleDescriptor-template.json
Fix saving links for user with limited permissions
[MODELINKS-112](https://issues.folio.org/browse/MODELINKS-112)
Add permissions for source records and search authorities
=> fix(instance-authority-linking): Add missing permissions to save links api

NEWS.md, descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/entlinks/controller/LinksSuggestionsController.java, src/main/java/org/folio/entlinks/controller/delegate/suggestion/LinksSuggestionServiceDelegate.java, src/main/java/org/folio/entlinks/controller/delegate/suggestion/LinksSuggestionServiceDelegateHelper.java, src/main/java/org/folio/entlinks/controller/delegate/suggestion/LinksSuggestionsByAuthorityId.java, src/main/java/org/folio/entlinks/controller/delegate/suggestion/LinksSuggestionsByAuthorityNaturalId.java, src/main/java/org/folio/entlinks/controller/delegate/suggestion/LinksSuggestionsServiceDelegateBase.java, src/main/java/org/folio/entlinks/service/links/InstanceAuthorityLinkingService.java, src/main/java/org/folio/entlinks/service/links/LinksSuggestionService.java, src/main/resources/swagger.api/mod-entities-links.yaml, src/test/java/org/folio/entlinks/controller/LinksSuggestionsIT.java, src/test/java/org/folio/entlinks/controller/delegate/suggestion/LinksSuggestionServiceDelegateHelperTest.java, src/test/java/org/folio/entlinks/controller/delegate/suggestion/LinksSuggestionsByAuthorityIdTest.java, src/test/java/org/folio/entlinks/controller/delegate/suggestion/LinksSuggestionsByAuthorityNaturalIdTest.java, src/test/java/org/folio/entlinks/controller/delegate/suggestion/LinksSuggestionsServiceDelegateTest.java, src/test/java/org/folio/entlinks/service/links/InstanceAuthorityLinkingServiceRenovateTest.java, src/test/java/org/folio/entlinks/service/links/InstanceAuthorityLinkingServiceTest.java, src/test/java/org/folio/entlinks/service/links/LinksSuggestionsServiceTest.java, src/test/java/org/folio/support/base/TestConstants.java, src/test/resources/mappings/mod-search.json
Extend "links suggestions" with some flag so it can search authorities by authorityId or naturalId based on provided flag value (for our case we need to search by authorityId)
Move "renovation" logic to a separate method so PUT endoint behave like before and renovation logic preserved for later purposes
[MODELINKS-113](https://issues.folio.org/browse/MODELINKS-113)
- Remove links renovation from 'PUT' links endpoint
- Extend links suggestions endpoint with 'authoritySearchField' to support suggestions by authorityId
=> fix(instance-authority-linking): Revert renovation logic and extend suggestions endpoint

src/main/java/org/folio/entlinks/controller/delegate/suggestion/LinksSuggestionsServiceDelegateBase.java, src/main/java/org/folio/entlinks/service/links/LinksSuggestionService.java, src/test/java/org/folio/entlinks/controller/LinksSuggestionsIT.java, src/test/java/org/folio/entlinks/controller/delegate/suggestion/LinksSuggestionsServiceDelegateTest.java, src/test/java/org/folio/entlinks/service/links/LinksSuggestionsServiceTest.java
Fix 'ignoreAutoLinkingEnabled' flag handling
- Check flag in delegate also
- Fill appropriate error when only autolinking error field
=> fix(links-suggestions): Fix 'ignoreAutoLinkingEnabled' flag handling

src/main/resources/permissions/mod-entities-links-permissions.csv
https://issues.folio.org/browse/MODELINKS-120
Don't add "mapping-metadata.get" and "mapping-rules.get" permissions to the system user because they belong to mod-source-record-manager that hasn't been enabled at this time.
=> MODELINKS-120: Don't add "mapping-metadata.get" and "mapping-rules.get"

descriptors/ModuleDescriptor-template.json, src/main/resources/permissions/mod-entities-links-permissions.csv, src/main/resources/swagger.api/schemas/authority-storage/authorityDto.yaml, src/test/java/org/folio/entlinks/controller/AuthorityControllerIT.java
Fix missed `user-tenants.collection.get` permission 
- add the permission to module descriptor for endpoints that support propagation
- add the permission to system-user permissions
- add required fields: source and naturalId for authority-storage API
=> fix(consortium): assign `user-tenants.collection.get` permission

src/main/java/org/folio/entlinks/config/JpaConfig.java, src/main/java/org/folio/entlinks/service/tenant/ExtendedTenantService.java
We can't build system-user context on POST _/tenant because dependant modules like mod-login and mod-authtoken are not ready to handle requests even if dependency is set in module descriptor
=> fix: change reference data behaviour

descriptors/ModuleDescriptor-template.json
_Add permission for getting user tenants for links suggestions API._
_Add missing permission_
[_MODELINKS-124_](https://issues.folio.org/browse/MODELINKS-124)
=> MODELINKS-124: Add missing permission for user-tenants

pom.xml, src/main/java/org/folio/entlinks/controller/ApiErrorHandler.java, src/main/java/org/folio/entlinks/exception/OptimisticLockingException.java, src/main/java/org/folio/entlinks/exception/type/ErrorType.java, src/main/java/org/folio/entlinks/service/authority/AuthorityService.java, src/test/java/org/folio/entlinks/controller/AuthorityControllerIT.java, src/test/java/org/folio/entlinks/service/authority/AuthorityServiceTest.java
_The version of Authority is not increased if there are no any changes in update operation. This contradicts with what we had before migrating Authority to mod-entities-links. Make the version of Authority change in every update operation._
_Indicate an authority entity as modified so that it gets updated by entity manager_
[_MODELINKS-132_](https://issues.folio.org/browse/MODELINKS-132)
=> MODELINKS-132: Fix Optimistic Locking and Make authority version always increase in update

pom.xml, src/main/java/org/folio/entlinks/controller/delegate/AuthorityServiceDelegate.java, src/main/java/org/folio/entlinks/controller/delegate/LinkingServiceDelegate.java, src/main/java/org/folio/entlinks/service/consortium/propagation/ConsortiumAuthorityDataStatsPropagationService.java, src/main/java/org/folio/entlinks/service/consortium/propagation/ConsortiumAuthorityPropagationService.java, src/main/java/org/folio/entlinks/service/consortium/propagation/ConsortiumLinksPropagationService.java, src/main/java/org/folio/entlinks/service/consortium/propagation/ConsortiumPropagationService.java, src/main/java/org/folio/entlinks/service/messaging/authority/InstanceAuthorityLinkUpdateService.java, src/main/java/org/folio/entlinks/service/messaging/authority/handler/UpdateAuthorityChangeHandler.java, src/main/java/org/folio/entlinks/service/messaging/authority/model/AuthorityChangeHolder.java, src/test/java/org/folio/entlinks/controller/delegate/AuthorityServiceDelegateTest.java, src/test/java/org/folio/entlinks/service/consortium/propagation/ConsortiumAuthorityDataStatsPropagationServiceTest.java, src/test/java/org/folio/entlinks/service/messaging/authority/InstanceAuthorityLinkUpdateServiceTest.java, src/test/java/org/folio/entlinks/service/messaging/authority/handler/UpdateAuthorityChangeHandlerTest.java
We should update shared links/bibs on member tenants when authority is updated/deleted on central tenant
- Retrieve source record only for central tenant
- Handle authority update for each of member tenants
=> fix(instance-authority-linking): Propagate central tenant authority links update to member tenants

NEWS.md, src/main/java/org/folio/entlinks/service/authority/AuthorityService.java, src/test/java/org/folio/entlinks/service/authority/AuthorityServiceTest.java
Fix updating authority's source file field to null failed
Set null when incoming records has null in source file field
https://issues.folio.org/browse/MODELINKS-143
=> fix(authority): updating authority's source file field to null

NEWS.md, src/main/resources/db/changelog/changes/v2.0/replace_authority_data.xml
Fix migration issue
Remove foreign key for authority_data_stat.
Decided to remove the FK because we will not be able to handle it due to moving deleted authorities to the archive table. We can't just remove rows from the stats table as this data still could be needed for the user.
_List any Jira issues related to this pull request._
_Discuss any research conducted during the development of this pull request. Include links to relevant blog posts, patterns, libraries, or addons that were used to solve the problem._
_If this pull request involves any visual changes or new features, consider including screenshots or GIFs to illustrate the changes._
=> fix: remove foreign key for authority_data_stat

NEWS.md, src/main/java/org/folio/entlinks/controller/delegate/AuthoritySourceFileServiceDelegate.java, src/main/java/org/folio/entlinks/domain/entity/AuthoritySourceFile.java, src/main/java/org/folio/entlinks/service/authority/AuthoritySourceFileService.java, src/main/java/org/folio/entlinks/service/consortium/propagation/ConsortiumAuthoritySourceFilePropagationService.java, src/test/java/org/folio/entlinks/controller/delegate/AuthoritySourceFileServiceDelegateTest.java, src/test/java/org/folio/entlinks/service/consortium/ConsortiumAuthoritySourceFilePropagationServiceTest.java, src/test/java/org/folio/support/base/TestConstants.java
Propagate authority source files to member tenants
- Propagate local authority source files on create/update/delete
- Set "consortium" source for shadow copies
- Prevent update/delete of shadow copies through API
[MODELINKS-175](https://issues.folio.org/browse/MODELINKS-175)
[central->member tenant migration script](https://wiki.folio.org/display/FOLIJET/Adding+a+new+member+tenant+to+consortium.+mod-entities-links+scope)
=> feat(consortium): Propagate authority source files to member tenants

src/main/java/org/folio/entlinks/domain/entity/AuthoritySourceFile.java, src/test/java/org/folio/entlinks/controller/AuthoritySourceFilesControllerIT.java
_Stackoverflow was detected when authority source file and authority copy instances in copy constructors were created with circular dependency._
_Modify Authority Source File Copy constructor by removing dependency for authority copy constructor._
[MODELINKS-197](https://issues.folio.org/browse/MODELINKS-197)
=> MODELINKS-197: Fix Authority Source File Copy Constructor

pom.xml
_Hibernate 6.4.1.Final has issue with saving or persisting JsonType fields and this was observed for authorities when they are persisted hibernate increases version property twice (one for insert and one for update)_
_Upgrade version of Spring-Boot without upgrading Hibernate._
[MODELINKS-206](https://folio-org.atlassian.net/browse/MODELINKS-206)
=> fix(deps): Upgrade spring-boot to 3.2.2 and not upgrade version of Hibernate

NEWS.md, doc/documentation.md, src/test/java/org/folio/entlinks/controller/AuthorityControllerIT.java
_Add possibility to filter authority records by (un)defined fields with cql query_
_Specifically handle Cql terms representing (un)defined fields of the DB table record._
[FOLSPRINGS-144](https://folio-org.atlassian.net/browse/FOLSPRINGS-144)
[MODELINKS-214](https://folio-org.atlassian.net/browse/MODELINKS-214)
=> MODELINKS-214: Add possibility to filter authority records by (un)defined fields with Cql query

NEWS.md, src/main/java/org/folio/entlinks/controller/delegate/AuthoritySourceFileServiceDelegate.java, src/main/java/org/folio/entlinks/service/authority/AuthoritySourceFileService.java, src/test/java/org/folio/entlinks/controller/AuthoritySourceFilesControllerIT.java, src/test/java/org/folio/entlinks/controller/delegate/AuthoritySourceFileServiceDelegateTest.java, src/test/java/org/folio/support/DatabaseHelper.java
Fix sequence deletion during deletion of authority source file, in order to properly create the new authority source file with the same prefix as previously deleted authority source file
Add method for deletion sequence of authority source file during its deletion
MODELINKS-211
=> fix(authority-prefix): delete sequence during deletion of authority-source-file

NEWS.md, src/main/java/org/folio/entlinks/controller/converter/AuthoritySourceFileMapper.java, src/main/java/org/folio/entlinks/controller/delegate/AuthoritySourceFileServiceDelegate.java, src/main/java/org/folio/entlinks/service/authority/AuthoritySourceFileService.java, src/main/resources/swagger.api/schemas/authority-source-file/authoritySourceFilePatchDto.yaml, src/test/java/org/folio/entlinks/controller/AuthoritySourceFilesControllerIT.java, src/test/java/org/folio/entlinks/controller/converter/AuthoritySourceFileMapperTest.java, src/test/java/org/folio/entlinks/controller/delegate/AuthoritySourceFileServiceDelegateTest.java, src/test/java/org/folio/entlinks/service/authority/AuthoritySourceFileServiceTest.java, src/test/java/org/folio/support/TestDataUtils.java
_Fix validation of authority source file prefix for PATCH request_
- do not allow to provide more than one preifx in request body for PATCH request
- add validation for the prefix same as for POST request
[MODELINKS-208](https://folio-org.atlassian.net/browse/MODELINKS-208)
=> fix(authority-source-files): Fix validation of authority source file prefix for PATCH request

NEWS.md, src/main/java/org/folio/entlinks/integration/kafka/EventProducer.java, src/main/java/org/folio/entlinks/utils/KafkaUtils.java, src/test/java/org/folio/entlinks/integration/kafka/EventProducerTest.java, src/test/java/org/folio/entlinks/utils/KafkaUtilsTest.java
_Use generic topic name instead of creating new for each tenant_
_Reuse KafkaUtils and respective method for topic name creation from folio-service-tools module_
[MODELINKS-213](https://folio-org.atlassian.net/browse/MODELINKS-213)
=> refactor(kafka-utils): Use generic topic name instead of creating new for each tenant

NEWS.md, src/main/resources/db/changelog/changelog-master.xml, src/main/resources/db/changelog/changes/v3.0/update-auto-linking_enabled.xml, src/test/java/org/folio/entlinks/controller/LinksSuggestionsIT.java, src/test/java/org/folio/support/DatabaseHelper.java, src/test/resources/linking-rules/instance-authority.json
Change default value for 6XX rules should have autoLinkingEnabled flag to true
Create SQL script which updates autoLinkingEnabled flag to true for 6xx fields
https://folio-org.atlassian.net/browse/MODELINKS-220
=> Change default value for 6XX rules should have autoLinkingEnabled flag to true

NEWS.md, src/main/java/org/folio/entlinks/domain/entity/Authority.java, src/main/java/org/folio/entlinks/domain/entity/AuthorityBase.java, src/main/java/org/folio/entlinks/domain/entity/AuthoritySourceFile.java, src/main/java/org/folio/entlinks/domain/entity/MetadataEntity.java, src/main/java/org/folio/entlinks/service/authority/AuthorityService.java, src/test/java/org/folio/entlinks/controller/AuthorityControllerIT.java, src/test/java/org/folio/entlinks/controller/InstanceAuthorityLinkStatisticsIT.java, src/test/java/org/folio/entlinks/service/authority/AuthorityServiceTest.java, src/test/java/org/folio/support/base/TestConstants.java, src/test/resources/mappings/users.json
_Capture the changes for authority record's ```updatedByUserId``` attribute before forming and sending the Update domain event DTO so that the DTO also has the right value at ```updatedByUserId``` (Authority Data Stat's ```startedByUserId``` attribute take the value from domain event's updatedByUserId). Also, fix the authority copy constructor to copy the authority source file._
_After the update/save of the authority changes immediately flush them so that Hibernate immediately updates the audit attributes._
[MODELINKS-219](https://folio-org.atlassian.net/browse/MODELINKS-219)
=> MODELINKS-219: Fix authority record update and updatedByUserId field assignment

NEWS.md, pom.xml
do not delete kafka topics if tenant collection topic feature is enabled
Use newest version of folio-service-tools
https://folio-org.atlassian.net/browse/MODELINKS-233
=> fix: do not delete kafka topics if tenant collection topic feature is enabled

src/main/resources/db/changelog/changelog-master.xml, src/main/resources/db/changelog/changes/v2.0/cleanup_authority_data_stat_constraint.xml
For some reason constraint that shouldn’t exist appeared on some envs. It’s needed to clean unneeded fk_authority_data_stat_authority_id` constraint from authority_data_stat table
Having this constraint may cause breaking bib-authority links
Create a liquibase script for deleting the constraint.
https://folio-org.atlassian.net/browse/MODELINKS-234
=> fix: cleanup authority_data_stat foreign-key

NEWS.md, src/main/java/org/folio/entlinks/controller/AuthorityController.java, src/main/java/org/folio/entlinks/controller/delegate/AuthorityArchiveServiceDelegate.java, src/main/java/org/folio/entlinks/controller/delegate/AuthorityServiceDelegate.java, src/main/resources/swagger.api/paths/authority-storage/authorities.yaml, src/main/resources/swagger.api/schemas/authority-storage/authorityIdDto.yaml, src/main/resources/swagger.api/schemas/authority-storage/authorityIdDtoCollection.yaml, src/test/java/org/folio/entlinks/controller/AuthorityControllerTest.java
Return only ids in response when idOnly=true
Create separate schema for ID-responses
https://folio-org.atlassian.net/browse/MODELINKS-237
=> fix(authority-storage): Return only ids in response when idOnly=true

NEWS.md, pom.xml, src/main/java/org/folio/entlinks/domain/entity/AuthorityIdentifier.java, src/main/java/org/folio/entlinks/domain/entity/AuthorityNote.java, src/main/java/org/folio/entlinks/domain/entity/HeadingRef.java
Repeated updates of same entity with the latest Hibernate versions caused by some fields are `jsonb` type
Add equals and hashcode for jsonb-converted entities
https://folio-org.atlassian.net/browse/MODELINKS-238
=> fix(authority-storage): fix issue that causes repeated update of same entity with latest Hibernate versions

NEWS.md, src/main/java/org/folio/entlinks/controller/delegate/AuthorityArchiveServiceDelegate.java, src/main/java/org/folio/entlinks/controller/delegate/AuthorityServiceDelegate.java, src/test/java/org/folio/entlinks/controller/delegate/AuthorityArchiveServiceDelegateTest.java, src/test/java/org/folio/entlinks/controller/delegate/AuthorityServiceDelegateTest.java
Fix totalRecords count when idOnly=true on authirity-storage/authorities
- Use page's totalElements instead of returned collection size for totalRecord of authorities
- Use page's totalElements instead of returned collection size for totalRecord of authority archives
[MODELINKS-239](https://folio-org.atlassian.net/browse/MODELINKS-239)
=> fix(authority): Fix totalRecords count when idOnly=true on authirity-storage/authorities

NEWS.md, src/main/java/org/folio/entlinks/service/messaging/authority/handler/DeleteAuthorityChangeHandler.java, src/test/java/org/folio/entlinks/service/messaging/authority/InstanceAuthorityLinkUpdateServiceTest.java, src/test/java/org/folio/entlinks/service/messaging/authority/handler/DeleteAuthorityChangeHandlerTest.java
_Fix handling of heading type change event for Authority with linked instances_
- keep deleting the existing link
- do not hard delete authority if handling heading type is changed.
[MODELINKS-242](https://folio-org.atlassian.net/browse/MODELINKS-242)
=> MODELINKS-242: Fix handling heading type change update event for Authority with linked instance

src/main/java/org/folio/entlinks/service/messaging/authority/handler/DeleteAuthorityChangeHandler.java, src/test/java/org/folio/entlinks/service/messaging/authority/handler/DeleteAuthorityChangeHandlerTest.java
_Do not hard delete authority when handling authority update event for heading type change_
_check domain event type when handling authority update event inside delete handler_
[MODELINKS-242](https://folio-org.atlassian.net/browse/MODELINKS-242)
=> MODELINKS-242: Fix handling update event for heading type change of authority with linked instance

src/main/resources/swagger.api/schemas/authority-storage/authorityDto.yaml, src/test/java/org/folio/entlinks/controller/converter/AuthorityMapperTest.java
Update serialization for AuthorityDto to not expose empty saftBroaderTerm, safrNarrowerTerm, saftEarlierHeading, saftLaterHeading in kafka messages.  It makes including extended mapping not noticeable for users who doesn't use this functionality. 
add com.fasterxml.jackson.annotation.JsonInclude.Include.NON_EMPTY annotation for saftBroaderTerm, safrNarrowerTerm, saftEarlierHeading, saftLaterHeading fields.
_List any Jira issues related to this pull request._
_Discuss any research conducted during the development of this pull request. Include links to relevant blog posts, patterns, libraries, or addons that were used to solve the problem._
_If this pull request involves any visual changes or new features, consider including screenshots or GIFs to illustrate the changes._
=> feature/MODELINKS-248 Do not show empty arrays for extended mapping

NEWS.md, src/main/resources/db/changelog/changelog-master.xml, src/main/resources/db/changelog/changes/v3.1/update-linking-rules-subfields.xml, src/test/java/org/folio/entlinks/integration/kafka/AuthorityEventListenerIT.java, src/test/resources/linking-rules/instance-authority.json
Update instance-authority linking rules to include v, x, y, z subfields
Create migration script for linking rules.
https://folio-org.atlassian.net/browse/MODELINKS-252
=> feat(linking-rules): update instance-authority linking rules to include v, x, y, z subfields

NEWS.md, src/main/java/org/folio/entlinks/controller/converter/AuthorityUtilityMapper.java, src/main/java/org/folio/entlinks/domain/entity/AuthorityConstants.java, src/main/resources/swagger.api/schemas/authority-storage/authorityDto.yaml, src/test/java/org/folio/entlinks/controller/AuthorityControllerIT.java, src/test/java/org/folio/entlinks/controller/converter/AuthorityMapperTest.java, src/test/java/org/folio/entlinks/controller/converter/AuthorityUtilityMapperTest.java, src/test/java/org/folio/support/TestDataUtils.java
[MODELINKS-267](https://folio-org.atlassian.net/browse/MODELINKS-267)
For ASA customer it is required to exclude subfields “i” and numeric subfields from the mapping for 5xx fields in Authority.
Example: 
```$w r $i Successor: $a Sri Lanka $4 http://rdaregistry.info/Elements/u/P60686 $0 (DLC)n 80061039 $0 http://id.loc.gov/authorities/names/n80061039 $1 http://id.loc.gov/rwo/agents/n80061039```
should be transformed to Sri Lanka, not to Successor: Sri Lanka http://rdaregistry.info/Elements/u/P60686
Additional fields with “Trunc” postfix are created like "saftGenreTermTrunc", "saftGeographicNameTrunc", etc. for the truncated mapping. Original saft* fields are kept without any changes.
_List any Jira issues related to this pull request._
_Discuss any research conducted during the …
=> MODELINKS-267: Extend Authority with saft* fields having custom mapping

src/main/java/org/folio/entlinks/service/links/LinksSuggestionsService.java, src/test/java/org/folio/entlinks/service/links/LinksSuggestionsServiceTest.java
Fix adding uncontrolled field when subfield modification exists in links suggestions
Add subfield modification to filtering logic
https://folio-org.atlassian.net/browse/MODELINKS-268
=> MODELINKS-268 Fix adding uncontrolled field when subfield modification exists in links suggestions

NEWS.md, src/main/java/org/folio/entlinks/controller/delegate/AuthorityServiceDelegate.java, src/main/java/org/folio/entlinks/service/authority/AuthorityArchiveService.java, src/main/java/org/folio/entlinks/service/authority/AuthorityService.java, src/main/java/org/folio/entlinks/service/authority/AuthorityServiceI.java, src/main/java/org/folio/entlinks/service/authority/AuthorityUpdateResult.java, src/main/java/org/folio/entlinks/service/authority/ConsortiumAuthorityService.java, src/test/java/org/folio/entlinks/controller/AuthorityControllerIT.java, src/test/java/org/folio/entlinks/controller/AuthoritySourceFilesControllerIT.java, src/test/java/org/folio/entlinks/controller/ConsortiumAuthoritySourceFilesIT.java, src/test/java/org/folio/entlinks/controller/ConsortiumLinksSuggestionsIT.java, src/test/java/org/folio/entlinks/controller/delegate/AuthorityServiceDelegateTest.java, src/test/java/org/folio/entlinks/service/authority/AuthorityServiceTest.java, src/test/java/org/folio/entlinks/service/authority/ConsortiumAuthorityServiceTest.java, src/test/java/org/folio/entlinks/service/consortium/ConsortiumAuthorityPropagationServiceIT.java, src/test/java/org/folio/support/base/IntegrationTestBase.java
Fix shared authority becoming shadow copy on central tenant
- Move consortium propagation out of central tenant transactional method
- Remove redundant AuthorityService methods
[MODELINKS-273](https://folio-org.atlassian.net/browse/MODELINKS-273)
The issue was with context mixup which caused central tenant record to be marked as consortium shadow copy.
Tested with consortium integration test (not included in a PR) which sequentially updates record 100 times and restarts multiple times. Before the fix - it failed in 2-7 run, now it succeeds event 20 runs in a row.
Manually tested on dev env by updating a record 20 times.
=> fix(consortium): Fix context mixup on data propagation

NEWS.md, src/main/java/org/folio/entlinks/service/authority/BulkAuthorityS3Client.java, src/test/java/org/folio/entlinks/service/authority/BulkAuthorityS3ClientTest.java
Close input stream on s3 file read
[MODELINKS-278](https://folio-org.atlassian.net/browse/MODELINKS-278)
=> fix(authority): Close input stream on s3 file read

NEWS.md, src/main/java/org/folio/entlinks/service/authority/AuthoritySourceFileService.java, src/main/java/org/folio/entlinks/service/authority/PropagationAuthoritySourceFileService.java
Authority source file sequence that is used for source file `hrid`'s is created and then queried with/for central tenant, thus there is not need to create it in member tenants schema and then populating the changes in patching/updating (local) source files. 
remove logic for updating/recreating source file sequence
[MODELINKS-244](https://folio-org.atlassian.net/browse/MODELINKS-244)
=> MODELINKS-244: Do not update (recreate) authority source file sequence for member tenant on updating source file

src/main/java/org/folio/entlinks/domain/repository/AuthoritySourceFileJdbcRepository.java, src/test/java/org/folio/entlinks/controller/ConsortiumAuthoritySourceFilesIT.java
_`selectable` field was missing in insert and update queries for propagating changes to ECS member tenants_
_include missing `selectable` field into SQL queries_
[MODELINKS-244](https://folio-org.atlassian.net/browse/MODELINKS-244)
=> fix(authority-source-files): In ECS, fix persisting authority source file selectable field

NEWS.md, src/main/java/org/folio/entlinks/config/KafkaConfiguration.java, src/main/resources/application.yaml, src/test/resources/application-test.yaml
Fix specification consumer startup
Set auto.offset.reset to EARLIEST so if mod-record-specifications starts first and sends specification updated event - mod-entities-links will set appropriate offset and consume event sent before it started
[MODELINKS-298](https://folio-org.atlassian.net/browse/MODELINKS-298)
=> fix(specification): Fix specification consumer startup

NEWS.md, src/main/resources/db/changelog/changelog-master.xml, src/main/resources/db/changelog/changes/v4.0/add-authority-source-file-index.xml
Fix long authority source file update/delete operation
- Create index for source_file_id in authority table
- Alter index for source_file_id in authority_archive table: set deduplicate_items=true
https://folio-org.atlassian.net/browse/MODELINKS-299
=> fix(authority-source-files): long update/delete operation

NEWS.md, src/main/java/org/folio/entlinks/domain/repository/AuthoritySourceFileJdbcRepository.java, src/main/java/org/folio/entlinks/utils/JdbcUtils.java, src/test/java/org/folio/entlinks/domain/repository/AuthoritySourceFileJdbcRepositoryIT.java, src/test/java/org/folio/entlinks/utils/JdbcUtilsTest.java
Fix issue when only first code is propagated in member tenants for authority source files.
- modify queries to save all codes
- add ITs
https://folio-org.atlassian.net/browse/MODELINKS-315
=> fix(authority-source-files): propagation to propagate all codes

NEWS.md, src/main/java/org/folio/entlinks/domain/entity/InstanceAuthorityLink.java, src/main/java/org/folio/entlinks/service/consortium/propagation/ConsortiumLinksPropagationService.java, src/test/java/org/folio/entlinks/controller/InstanceAuthorityLinksIT.java, src/test/java/org/folio/entlinks/controller/delegate/LinkingServiceDelegateTest.java, src/test/java/org/folio/entlinks/service/consortium/ConsortiumInstanceAuthorityLinksIT.java, src/test/java/org/folio/entlinks/service/consortium/ConsortiumLinksPropagationServiceTest.java, src/test/java/org/folio/support/base/IntegrationTestBase.java
After instance-authority link record is created in central tenant's DB it fails to do the same for member tenants. Due to the latest changes hibernate assumes that if generated id column is set with a value for an entity then it already exists in DB and if does not exists it throws optimistic locking exception thinking entity is modified/removed while it is being persisted
copy instances to be persisted without getting their id before propagation
[MODELINKS-319](https://folio-org.atlassian.net/browse/MODELINKS-319)
If the id field is provided, Hibernate assumes the entity already exists in the database. If no matching row is found, Hibernate interprets this as the entity having been deleted by another transaction, resulting in an OptimisticLockException. …
=> MODELINKS-319: Fix propagation of instance-authority link record creation/update to member tenants

NEWS.md, src/main/java/org/folio/entlinks/integration/kafka/AuthorityEventListener.java, src/main/java/org/folio/entlinks/utils/HeaderUtils.java, src/test/java/org/folio/entlinks/integration/kafka/AuthorityEventListenerTest.java, src/test/java/org/folio/entlinks/utils/HeaderUtilsTest.java
Fix `null` `userId` in `updatedByUser` field of linked instance after linked authority field update on eureka env where system user is disabled for module.
Pass userId header to execution context on authority update so link update events has userId when system user is disabled
[UIIN-3305](https://folio-org.atlassian.net/browse/UIIN-3305)
[FOLSPRINGS-195](https://folio-org.atlassian.net/browse/FOLSPRINGS-195)
=> fix(authority-instance-link): Pass userId from authority kafka event to link update events

NEWS.md, src/main/java/org/folio/entlinks/config/constants/CacheNames.java, src/main/java/org/folio/entlinks/service/links/InstanceAuthorityLinkingRulesService.java, src/test/java/org/folio/entlinks/service/links/InstanceAuthorityLinkingRulesServiceTest.java
Remove cache to fix outdated linking rules in case of multi-instance deployment
https://folio-org.atlassian.net/browse/MODELINKS-333
=> feat(linking-rules): remove cache for linking rules

descriptors/ModuleDescriptor-template.json
to accomplish the move of the mod-source-record-manager module from app-platform-complete to app-data-import application, it is necessary to temporarily change dependency on `mapping-rules-provider` interface to optional until mod-entities-links is moved to its own separate application.
[MODELINKS-337](https://issues.folio.org/browse/MODELINKS-337)
=> chore: change dependency on `mapping-rules-provider` interface to optional
