descriptors/DeploymentDescriptor-template.json
=> Fix deployment descriptor

descriptors/ModuleDescriptor-template.json
=> Fix *.all permission

descriptors/ModuleDescriptor-template.json
=> Fix permissions

Dockerfile
Add apk upgrade for docker file
https://issues.folio.org/browse/MODELINKS-7
=> MODELINKS-7 apk upgrade

src/main/java/org/folio/entlinks/service/InstanceLinkService.java, src/test/java/org/folio/entlinks/controller/InstanceLinksIT.java, src/test/java/org/folio/entlinks/service/InstanceLinkServiceTest.java, src/test/java/org/folio/support/TestUtils.java
Update existing links when only naturalId or sufields changed
* Extend logic of preparing links to save
* add unit test
=> MODELINKS-2 Update existing links

doc/documentation.md, pom.xml, src/main/java/org/folio/entlinks/EntityLinksApplication.java, src/main/java/org/folio/entlinks/config/KafkaConfiguration.java, src/main/java/org/folio/entlinks/service/LinksTenantService.java, src/main/resources/application.yaml, src/test/java/org/folio/entlinks/service/LinksTenantServiceTest.java, src/test/java/org/folio/support/base/IntegrationTestBase.java, src/test/java/org/folio/support/extension/EnableKafka.java, src/test/java/org/folio/support/extension/impl/KafkaContainerExtension.java, src/test/java/org/folio/support/extension/impl/PostgresContainerExtension.java, src/test/resources/application-test.yaml
Implement mechanism of topic creation
* Use folio-service-tools-spring-dev lib for Kafka topic creation
=> MODELINKS-15 Implement mechanism of topic creation

descriptors/ModuleDescriptor-template.json
Add required interfaces to module descriptor
=> MODELINKS-26 Add required interfaces to module descriptor

PULL_REQUEST_TEMPLATE.md, src/main/resources/application.yaml
_Logging should be improved for more productive troubleshooting._
- Check that log4j2.properties doesn't exist or it is aligned with https://wiki.folio.org/display/DD/Folio+logging+solution
- Enable the /loggers endpoint in our application.properties file by adding the following lines:
- management.endpoints.web.exposure.include=loggers
- management.endpoint.loggers.enabled=true
- The version of the folio-spring-base should be updated (see [FOLSPRINGB-45](https://issues.folio.org/browse/FOLSPRINGB-45))
- Add step "Check logging" to PULL_REQUEST_TEMPLATE.md
https://issues.folio.org/browse/MODELINKS-22
=> MODELINKS-22 - Logging improvement - Configuration

src/main/java/org/folio/entlinks/repository/InstanceLinkRepository.java, src/test/java/org/folio/entlinks/controller/InstanceLinksIT.java
- Distinct results by instanceId
https://issues.folio.org/browse/MODELINKS-27
=> MODELINKS-27 Return distinct count by instanceId on /count endpoint

src/main/resources/db/changelog/changes/v1.0/linking_rules.xml, src/main/resources/db/changelog/changes/v1.0/update-instance-authority-linking-rules.sql, src/test/resources/linking-rules/instance-authority.json
Update rules according [spreadsheat](https://ebscoind-my.sharepoint.com/:x:/g/personal/kgambrell_corp_epnet_com/ETxsofuRwqJOppFchFQ67JEBemilYSf2FeGg-O-JzhaWqQ?e=4%3AADM3kc&at=9&CID=99A36D08-E864-4D18-A393-257CBED70A65&wdLOR=cD4558105-9DB9-442F-962C-E83ACB41152B)
https://issues.folio.org/browse/MODELINKS-24
=> MODELINKS-24 Update instance-authority linking rules

descriptors/ModuleDescriptor-template.json, doc/documentation.md, src/main/resources/application.yaml
=> Update module documentation

src/main/resources/permissions/mod-entities-links-permissions.csv
Add system-user permissions for links update
Add permissions:
mapping-metadata.get
inventory-storage.instances.item.get
inventory-storage.instances.item.put
=> MODELINKS-39 Add system-user permissions for links update

src/main/java/org/folio/entlinks/domain/entity/AuthorityDataStat.java, src/main/java/org/folio/entlinks/domain/entity/InstanceAuthorityLink.java, src/main/java/org/folio/entlinks/service/links/AuthorityDataStatService.java, src/main/java/org/folio/entlinks/service/messaging/authority/model/FieldChangeHolder.java, src/main/resources/db/changelog/changes/v1.0/initial_schema.xml, src/test/java/org/folio/entlinks/integration/kafka/AuthorityInventoryEventListenerIT.java, src/test/java/org/folio/entlinks/service/links/AuthorityDataStatServiceTest.java, src/test/java/org/folio/entlinks/service/messaging/authority/model/FieldChangeHolderTest.java
Send empty subfield changes to update bib event. This is needed to remove them from bib record.
Change event creation logic
Update logic of statuses and updateAt saving
=> MODELINKS-44 Send empty subfield changes to update bib event

pom.xml, src/main/java/org/folio/entlinks/controller/delegate/InstanceAuthorityStatServiceDelegate.java, src/main/java/org/folio/entlinks/domain/repository/AuthorityDataStatRepository.java, src/main/java/org/folio/entlinks/service/links/AuthorityDataStatService.java, src/test/java/org/folio/entlinks/controller/InstanceAuthorityLinkStatisticsIT.java, src/test/java/org/folio/entlinks/controller/delegate/InstanceAuthorityStatServiceDelegateTest.java, src/test/java/org/folio/support/TestUtils.java
_Make corrections to new endpoint functionality._
_Improved places where causing error_
[https://issues.folio.org/browse/MODELINKS-38](https://issues.folio.org/browse/MODELINKS-34)
=> MODELINKS-34: NPE problem fixed

src/main/java/org/folio/entlinks/domain/entity/InstanceAuthorityLink.java, src/main/resources/db/changelog/changes/v1.0/initial_schema.xml, src/main/resources/swagger.api/mod-entities-links.yaml, src/test/java/org/folio/entlinks/controller/InstanceAuthorityLinksIT.java, src/test/java/org/folio/support/TestUtils.java, src/test/resources/linking-rules/instance-authority.json
Add linkingRuleId into links and linking-rules APIs
* Update db scripts to add linkingRuleId column to links table
* Update request/response bodies of links and linking-rules APIs
=> MODELINKS-49 Add linkingRuleId into links and linking-rules APIs

pom.xml, src/main/resources/application.yaml
It's required to show "Automated linking update" in instance record in last updated by section.
Change lastname of system-user. It will be enough as UI uses lastname for view
=> MODELINKS-52 Change system-user lastname to "Automated linking update"

pom.xml
Bump folio-service-tools to v3.1.0-SNAPSHOT
=> Bump folio-service-tools to v3.1.0-SNAPSHOT

src/main/resources/permissions/mod-entities-links-permissions.csv
Add users get permission to system-user
=> MODELINKS-52 Add users get permission to system-user

doc/documentation.md, src/main/java/org/folio/entlinks/config/properties/InstanceStorageProperties.java, src/main/java/org/folio/entlinks/integration/internal/InstanceStorageService.java, src/main/resources/application.yaml, src/test/java/org/folio/entlinks/integration/internal/InstanceStorageServiceTest.java
Decrease instances batch size from 100 to 50 items
https://issues.folio.org/browse/MODELINKS-78
=> MODELINKS-78 Decrease default instance batch size

.github/workflows/add-comment.yml
_Describe the purpose of the pull request._
_How does this change fulfill the purpose?_
=> test comment action

.github/workflows/api-doc.yml, .github/workflows/api-lint.yml, .github/workflows/api-schema-lint.yml, Jenkinsfile, README.md, src/main/resources/swagger.api/mod-entities-links.yaml
[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).
=> FOLIO-3678 MODELINKS-96 Use GitHub Workflows api-lint and api-schema-lint and api-doc

src/main/java/org/folio/entlinks/controller/delegate/LinksSuggestionsServiceDelegate.java, src/main/java/org/folio/entlinks/service/links/LinksSuggestionService.java, src/main/java/org/folio/entlinks/service/links/model/LinksSuggestionErrorCode.java, src/test/java/org/folio/entlinks/controller/LinksSuggestionsIT.java, src/test/java/org/folio/entlinks/service/links/LinksSuggestionsServiceTest.java, src/test/resources/mappings/mod-search.json
fix(automate-linking): Handle no authorities found case
- Handle no authorities found case
- Fix grammar mistake
Closes MODELINKS-94
=> fix(automate-linking): Handle no authorities found case

NEWS.md, descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/entlinks/controller/LinksSuggestionsController.java, src/main/java/org/folio/entlinks/controller/delegate/suggestion/LinksSuggestionServiceDelegate.java, src/main/java/org/folio/entlinks/controller/delegate/suggestion/LinksSuggestionsServiceDelegateBase.java, src/main/java/org/folio/entlinks/service/links/LinksSuggestionService.java, src/main/resources/swagger.api/mod-entities-links.yaml, src/test/java/org/folio/entlinks/controller/LinksSuggestionsIT.java, src/test/java/org/folio/entlinks/controller/delegate/suggestion/LinksSuggestionsServiceDelegateTest.java, src/test/java/org/folio/entlinks/service/links/LinksSuggestionsServiceTest.java, src/test/java/org/folio/support/base/TestConstants.java
Add ignoreAutoLinkingEnabled flag to api
[MODELINKS-114](https://issues.folio.org/browse/MODELINKS-114)
Add ignoreAutoLinkingEnabled flag to api
=> feat(links-suggestions): Add ignoreAutoLinkingEnabled flag to api

descriptors/ModuleDescriptor-template.json, src/main/resources/permissions/mod-entities-links-permissions.csv
Fix  circular dependency mod-source-record-manager and mapping-rules.get
https://issues.folio.org/browse/MODELINKS-120
=> fix(authority): circular dependency mod-source-record-manager and mapping-rules.get

src/main/java/org/folio/entlinks/domain/entity/AuthoritySourceFileCode.java, src/main/java/org/folio/entlinks/domain/repository/AuthoritySourceFileCodeRepository.java, src/main/java/org/folio/entlinks/service/links/LinksSuggestionService.java, src/main/java/org/folio/entlinks/service/links/RenovateLinksService.java, src/test/java/org/folio/entlinks/controller/LinksSuggestionsIT.java, src/test/java/org/folio/entlinks/service/links/LinksSuggestionsServiceTest.java, src/test/java/org/folio/support/TestDataUtils.java
_Base URL not shown in "$0" of linked MARC bib field after linking and reopening for edit._
_Fix DB query method for getting right authority source file code_
[MODELINKS-125](issues.folio.org/browse/MODELINKS-125)
=> fix(mod-entities-links): Fix links authority suggestions

src/main/resources/permissions/mod-entities-links-permissions.csv
Fix missing permission issue
Add permission to system user
=> fix(consortium): Add source-storage.records.fetch permission to system user

NEWS.md, src/main/java/org/folio/entlinks/controller/delegate/LinkingServiceDelegate.java, src/main/java/org/folio/entlinks/service/consortium/propagation/ConsortiumLinksPropagationService.java, src/main/java/org/folio/entlinks/service/consortium/propagation/model/LinksPropagationData.java, src/test/java/org/folio/entlinks/controller/delegate/LinkingServiceDelegateTest.java, src/test/java/org/folio/entlinks/service/consortium/ConsortiumLinksPropagationServiceTest.java
Fix empty links list propagation
Pass instanceId together with links list instead of extracting from first link
Discovered during [MODELINKS-164](https://issues.folio.org/browse/MODELINKS-164) investigation
=> fix(links-update): Fix empty links list propagation

src/main/java/org/folio/entlinks/config/constants/ErrorCode.java, src/main/java/org/folio/entlinks/controller/ApiErrorHandler.java, src/main/java/org/folio/entlinks/service/authority/AuthoritySourceFileService.java, src/main/resources/db/changelog/changes/v2.1/add_authority_source_file_new_fields.xml, src/main/resources/swagger.api/schemas/authority-source-file/authoritySourceFilePostDto.yaml, src/test/java/org/folio/entlinks/controller/AuthoritySourceFilesControllerIT.java, src/test/java/org/folio/entlinks/service/authority/AuthoritySourceFileServiceTest.java
_Fix constraint violation cases for request body of Authority Source Files POST API_
_Handle respective exceptions/errors and return appropriate error responses with right codes._
[MODELINKS-123](https://issues.folio.org/browse/MODELINKS-123)
=> MODELINKS-123: Fix constrain violations for Authority Source File POST API Request 

NEWS.md, src/main/java/org/folio/entlinks/controller/delegate/AuthorityServiceDelegate.java, src/test/java/org/folio/entlinks/controller/delegate/AuthorityServiceDelegateTest.java
Prohibit update/delete of authority consortium shadow copy
[MODELINKS-174](https://issues.folio.org/browse/MODELINKS-174)
=> feat(consortium): Prohibit update/delete of authority consortium shadow copy

src/main/java/org/folio/entlinks/service/authority/AuthoritySourceFileService.java, src/test/java/org/folio/entlinks/service/authority/AuthoritySourceFileServiceTest.java
Fix authority source file propagation
Allow "CONSORTIUM" source file to be created on a Service layer
[MODELINKS-175](https://issues.folio.org/browse/MODELINKS-175)
=> fix(consortium): Fix authority source file propagation

src/main/resources/swagger.api/schemas/authority-source-file/authoritySourceFileDto.yaml, src/test/java/org/folio/entlinks/controller/converter/AuthoritySourceFileMapperTest.java
Add 'consortium' to authority source file 'source' enum
[MODELINKS-184](https://issues.folio.org/browse/MODELINKS-184)
Not upgrading interface version as it was already increased in previous commit
=> fix(authority-source-files): Add 'consortium' to authority source file 'source' enum

src/main/java/org/folio/entlinks/service/authority/AuthorityNoteTypeService.java, src/main/java/org/folio/entlinks/service/authority/AuthoritySourceFileService.java, src/main/java/org/folio/entlinks/service/dataloader/ReferenceDataLoader.java, src/test/java/org/folio/entlinks/service/authority/AuthorityNoteTypeServiceTest.java, src/test/java/org/folio/entlinks/service/authority/AuthoritySourceFileServiceTest.java, src/test/java/org/folio/entlinks/service/dataloader/ReferenceDataLoaderTest.java
_Refactor Authority Source File creation_
- remove source enum field validation as only authority source files with LOCAL source field value is being created by REST endpoint
- make use of the refactored service method for reference authority source files creation as well (with FOLIO source field value)
[MODELINKS-185](https://issues.folio.org/browse/MODELINKS-185)
=> MODELINKS-185: Refactor Authority Source File Creation

NEWS.md, src/main/java/org/folio/entlinks/controller/delegate/AuthorityArchiveServiceDelegate.java, src/main/java/org/folio/entlinks/domain/entity/Authority.java, src/main/java/org/folio/entlinks/domain/entity/AuthorityBase.java, src/main/java/org/folio/entlinks/service/consortium/propagation/ConsortiumAuthorityArchivePropagationService.java, src/main/java/org/folio/entlinks/service/links/LinksSuggestionService.java, src/test/java/org/folio/entlinks/controller/delegate/AuthorityArchiveServiceDelegateTest.java, src/test/java/org/folio/entlinks/service/consortium/ConsortiumAuthorityArchivePropagationServiceTest.java, src/test/java/org/folio/entlinks/service/consortium/ConsortiumAuthorityPropagationServiceIT.java
_Propagate hard-delete or expiration of authority archive records for member tenants_
_Use same approach as for other entities and actions._
Closes: [MODELINKS-195](https://issues.folio.org/browse/MODELINKS-195)
=> MODELINKS-195: Propogate hard-delete of authority records

.github/dependabot.yml
change dependabot check interval
=> chore: change dependabot check interval

src/main/java/org/folio/entlinks/domain/entity/AuthoritySourceFile.java, src/test/java/org/folio/entlinks/controller/delegate/AuthoritySourceFileServiceDelegateTest.java
Fix issue of OOM
Remove bidirectional connection between source file and authority
https://issues.folio.org/browse/MODELINKS-200
=> fix(authority): remove bidirectional connection between source file and authority

descriptors/ModuleDescriptor-template.json
_Add missing permission to delete authority archives from member tenants_
_Add permission for API /authority-storage/expire/authorities_
Closes: [MODELINKS-195](https://issues.folio.org/browse/MODELINKS-195)
=> MODELINKS-195: Add missing permission to delete authority archives from member tenants

NEWS.md, pom.xml, src/main/java/org/folio/entlinks/controller/delegate/AuthoritySourceFileServiceDelegate.java, src/main/java/org/folio/entlinks/service/authority/AuthoritySourceFileService.java, src/test/java/org/folio/entlinks/controller/AuthorityControllerIT.java, src/test/java/org/folio/entlinks/controller/AuthoritySourceFilesControllerIT.java, src/test/java/org/folio/entlinks/controller/delegate/AuthoritySourceFileServiceDelegateTest.java, src/test/java/org/folio/entlinks/service/authority/AuthoritySourceFileServiceTest.java, src/test/java/org/folio/support/base/IntegrationTestBase.java
_Do not allow modifying and deleting Authority Source File referenced by local Authority of some member tenant in ECS_
_Modify checking of referenced authorities._
[MODELINKS-217](https://issues.folio.org/browse/MODELINKS-217)
=> fix(authority-source-files): Fix modifying and deleting of source file referenced by authority of member tenant

pom.xml
Fix `Caused by: java.lang.ClassNotFoundException: software.amazon.awssdk.auth.credentials.AwsCredentials` when S3_IS_AWS env var set to `true`
Add required dependency
MODELINKS-224
=> build: fix building S3-client for AWS credentials

NEWS.md, pom.xml, src/main/java/org/folio/entlinks/service/messaging/authority/handler/DeleteAuthorityChangeHandler.java, src/test/java/org/folio/entlinks/service/messaging/authority/InstanceAuthorityLinkUpdateServiceTest.java, src/test/java/org/folio/entlinks/service/messaging/authority/handler/DeleteAuthorityChangeHandlerTest.java
_Release v3.0.2_
[MODELINKS-246](https://folio-org.atlassian.net/browse/MODELINKS-246)
[MODELINKS-247](https://folio-org.atlassian.net/browse/MODELINKS-247)
=> release v3.0.2

NEWS.md, descriptors/ModuleDescriptor-template.json
Align dependencies with the new instance-storage interface version
https://folio-org.atlassian.net/browse/MODELINKS-256
=> build: bump the instance-storage interface to support both 10.0 and 11.0

.github/workflows/api-doc.yml
_Fix list of APIs file generation_
_modify api-doc.yml_
[MODELINKS-254](https://folio-org.atlassian.net/browse/MODELINKS-254)
=> MODELINKS-254: Fix dead link in config-doc.json

src/main/java/org/folio/entlinks/config/KafkaConfiguration.java, src/main/java/org/folio/entlinks/integration/kafka/SpecificationChangedEventListener.java, src/main/java/org/folio/entlinks/service/tenant/MarcSpecificationUpdateService.java, src/main/resources/application.yaml, src/test/java/org/folio/entlinks/integration/kafka/SpecificationChangedEventListenerTest.java, src/test/resources/application-test.yaml
define $9 subfield definitions for MARC bibliographic records if spec fully updated
Consume specification updated events and send $9 updates if it fully updated.
MODELINKS-252
=> feat: define $9 subfield definitions for MARC bibliographic records if spec fully updated

src/main/resources/permissions/mod-entities-links-permissions.csv
_Describe the purpose of this pull request. Why is this change necessary? What problem does it solve?_
_How does this change fulfill the purpose? Provide a high-level overview of the technical approach taken to address the problem._
_List any Jira issues related to this pull request._
_Discuss any research conducted during the development of this pull request. Include links to relevant blog posts, patterns, libraries, or addons that were used to solve the problem._
_If this pull request involves any visual changes or new features, consider including screenshots or GIFs to illustrate the changes._
=> MODELINKS-257 Update source-storage-source-records and permission names

NEWS.md, pom.xml
prepare for next development iteration v3.1.0
=> chore: prepare for next development iteration v3.1.0

NEWS.md, src/main/java/org/folio/entlinks/controller/converter/SourceContentMapper.java, src/main/java/org/folio/entlinks/controller/delegate/suggestion/LinksSuggestionsByAuthorityId.java, src/main/java/org/folio/entlinks/controller/delegate/suggestion/LinksSuggestionsByAuthorityNaturalId.java, src/main/java/org/folio/entlinks/controller/delegate/suggestion/LinksSuggestionsServiceDelegateBase.java, src/main/java/org/folio/entlinks/integration/dto/AuthorityParsedContent.java, src/main/java/org/folio/entlinks/integration/dto/FieldParsedContent.java, src/main/java/org/folio/entlinks/integration/dto/ParsedSubfield.java, src/main/java/org/folio/entlinks/service/links/AuthorityRuleValidationService.java, src/main/java/org/folio/entlinks/service/links/LinksSuggestionsService.java, src/main/java/org/folio/entlinks/utils/FieldUtils.java, src/test/java/org/folio/entlinks/controller/ConsortiumLinksSuggestionsIT.java, src/test/java/org/folio/entlinks/controller/LinksSuggestionsIT.java, src/test/java/org/folio/entlinks/controller/converter/SourceContentMapperTest.java, src/test/java/org/folio/entlinks/controller/delegate/suggestion/LinksSuggestionsByAuthorityIdTest.java, src/test/java/org/folio/entlinks/controller/delegate/suggestion/LinksSuggestionsByAuthorityNaturalIdTest.java, src/test/java/org/folio/entlinks/controller/delegate/suggestion/LinksSuggestionsServiceDelegateHelperTest.java, src/test/java/org/folio/entlinks/controller/delegate/suggestion/LinksSuggestionsServiceDelegateTest.java, src/test/java/org/folio/entlinks/integration/dto/AuthorityParsedContentTest.java, src/test/java/org/folio/entlinks/integration/dto/FieldParsedContentTest.java, src/test/java/org/folio/entlinks/service/links/LinksSuggestionsServiceTest.java, src/test/java/org/folio/support/TestUtils.java, src/test/resources/mappings/source-storage.json
Linked bib field controlled subfield box should honor controlled MARC authority subfield order
Introduce ParsedSubfield class and refactor subfield handling to use character-code-based maps. Update related service classes and tests to handle new subfield structure and improve link suggestion logic.
https://folio-org.atlassian.net/browse/MODELINKS-268
=> MODELINKS-268 Refactor subfield handling and improve link suggestion logic

NEWS.md, src/main/resources/db/changelog/changelog-master.xml, src/main/resources/db/changelog/changes/v3.1/migrate-deleted-authorities.xml
Add migration for deleted authorities
Include a new changelog to create an index on the 'deleted' column and migrate deleted records to 'authority_archive'.
https://folio-org.atlassian.net/browse/MODELINKS-270
=> MODELINKS-270 Add migration for deleted authorities

NEWS.md, descriptors/ModuleDescriptor-template.json
Add missing interface source-storage-batch dependency in module descriptor
https://folio-org.atlassian.net/browse/MODELINKS-275
=> MODELINKS-275 Add missing interface `source-storage-batch` dependency in module descriptor

NEWS.md, src/main/java/org/folio/entlinks/integration/internal/MarcSpecificationUpdateService.java, src/main/java/org/folio/entlinks/integration/kafka/SpecificationChangedEventListener.java, src/main/java/org/folio/entlinks/service/tenant/ExtendedTenantService.java, src/test/java/org/folio/entlinks/integration/internal/MarcSpecificationUpdateServiceTest.java, src/test/java/org/folio/entlinks/integration/kafka/SpecificationChangedEventListenerTest.java, src/test/java/org/folio/entlinks/service/tenant/ExtendedTenantServiceTest.java
Filter full specification updated event based on specification family and profile 
https://folio-org.atlassian.net/browse/MODELINKS-276
=> MODELINKS-276 Filter full specification updated event based on specification `family` and `profile`

NEWS.md, src/main/resources/db/changelog/changelog-master.xml, src/main/resources/db/changelog/changes/v3.1/update-authority-source-file-prefixes.xml, src/main/resources/reference-data/authority-source-files/AAT.json
Add aatfg to the list of prefixes for Art & Architecture authority file
Create migration script
https://folio-org.atlassian.net/browse/MODELINKS-272
=> MODELINKS-272 Add aatfg to the list of prefixes for Art & Architecture authority file

.github/workflows/api-doc.yml, NEWS.md
Fix documentation generation github workflow
- Fix generated filename
- Fix filepath for release builds
[MODELINKS-291](https://folio-org.atlassian.net/browse/MODELINKS-291)
=> docs(api-docs): Fix documentation generation github workflow

NEWS.md, descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/entlinks/controller/delegate/InstanceAuthorityStatServiceDelegate.java, src/main/java/org/folio/entlinks/service/tenant/ExtendedTenantService.java, src/test/java/org/folio/support/TestDataUtils.java, src/test/resources/mappings/users.json
[MODELINKS-292](https://folio-org.atlassian.net/browse/MODELINKS-292) Add users.item.put to tenant endpoint module permissions
=> chore(permissions): Add users.item.put to tenant endpoint module permissions

NEWS.md, src/main/java/org/folio/entlinks/controller/converter/AuthorityUtilityMapper.java, src/main/java/org/folio/entlinks/domain/entity/AuthorityConstants.java, src/main/resources/swagger.api/schemas/authority-storage/authorityDto.yaml, src/test/java/org/folio/entlinks/controller/converter/AuthorityUtilityMapperTest.java
_Describe the purpose of this pull request. Why is this change necessary? What problem does it solve?_
Extend Authority with namedEvent, sftNamedEvent, and saftNamedEvent fields
[MODELINKS-294](https://folio-org.atlassian.net/browse/MODELINKS-294)
=> MODELINKS-294: Extend Authority with namedEvent, sftNamedEvent, and saftNamedEvent fields

.github/workflows/api-doc.yml
Fix release docs generation
Use `find` for `config-doc.json` lookup and pass the result to `jq`
[MODELINKS-291](https://folio-org.atlassian.net/browse/MODELINKS-291)
=> fix(api-docs): Fix release docs generation

NEWS.md, pom.xml, src/main/java/org/folio/entlinks/controller/converter/AuthorityUtilityMapper.java, src/main/java/org/folio/entlinks/domain/entity/AuthorityConstants.java, src/main/resources/swagger.api/schemas/authority-storage/authorityDto.yaml, src/test/java/org/folio/entlinks/controller/converter/AuthorityUtilityMapperTest.java
Extend Authority with additional fields
- Extend authority with chronTerm, mediumPerfTerm, generalSubdivision, geographicSubdivision, chronSubdivision, formSubdivision
- Extend authority with "Trunc" versions of fields + namedEventTrunc
[MODELINKS-117](https://folio-org.atlassian.net/browse/MODELINKS-117)
=> feat(authority): Extend Authority with additional fields

descriptors/ModuleDescriptor-template.json, pom.xml
Increase default memory allocation
https://folio-org.atlassian.net/browse/MODELINKS-310
=> build: increase default memory allocation

NEWS.md, pom.xml, src/main/resources/db/changelog/changelog-master.xml, src/main/resources/db/changelog/changes/v4.0/update-linking-rules-subfields.xml, src/test/resources/linking-rules/instance-authority.json
Extend linking rules for 110/111 fields
https://folio-org.atlassian.net/browse/MODELINKS-311
=> fix(linking-rules): extend linking rules for 110/111 fields

NEWS.md, pom.xml
prepare for next development iteration v4.1.0
=> chore: prepare for next development iteration v4.1.0

NEWS.md, descriptors/ModuleDescriptor-template.json
remove unused search.authorities.collection.get permission
https://folio-org.atlassian.net/browse/MODELINKS-336
=> build: remove unused search.authorities.collection.get permission
